# Generated by Django 5.0.6 on 2024-08-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', 'new1_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number_of_person',
            new_name='number_of_bed',
        ),
    ]
