# Generated by Django 5.0.6 on 2024-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amenitiesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='roomsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=120)),
                ('room_type', models.CharField(blank=True, max_length=60)),
                ('bed_type', models.CharField(blank=True, max_length=60)),
                ('price', models.CharField(blank=True, max_length=120)),
                ('availability', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('amenities', models.ManyToManyField(to='rooms.amenitiestable')),
            ],
        ),
    ]
