# Generated by Django 5.0.6 on 2024-08-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_rename_number_of_person_room_number_of_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.bedtype'),
        ),
    ]
