# Generated by Django 5.0.6 on 2024-08-15 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('rooms', '0002_alter_room_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_fk', to='organization.hotel'),
            preserve_default=False,
        ),
    ]
