# Generated by Django 5.0.6 on 2024-08-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('rooms', '0003_bedtype_roomameneties_roomservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedtype',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bedtype_fk', to='organization.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomameneties',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_amentities_fk', to='organization.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomservices',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services_fk', to='organization.hotel'),
            preserve_default=False,
        ),
    ]
