# Generated by Django 5.0.6 on 2024-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roombooking_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capcity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_check_out',
            field=models.BooleanField(default=False),
        ),
    ]
