# Generated by Django 5.0.6 on 2024-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_capcity_roombooking_is_check_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capcity',
            new_name='capacity',
        ),
    ]
