# Generated by Django 5.0.6 on 2024-09-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_alter_category_status_alter_menuitem_status'),
        ('rooms', '0005_rename_capcity_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.menuitem'),
        ),
    ]
