# Generated by Django 5.0.6 on 2024-09-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_alter_category_status_alter_menuitem_status'),
        ('rooms', '0006_remove_orderitem_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_order', to='kitchen.kitchen'),
            preserve_default=False,
        ),
    ]
