# Generated by Django 5.0.6 on 2024-07-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftable',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
