# Generated by Django 5.0.6 on 2024-08-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_stafftable_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafftable',
            old_name='nationlaity',
            new_name='nationality',
        ),
    ]
