# Generated by Django 5.0.6 on 2024-09-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenfinancialstatement',
            name='kitchen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='kitchen.kitchen'),
            preserve_default=False,
        ),
    ]
