# Generated by Django 5.0.6 on 2024-09-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_kitchenexpense_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenexpense',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='kitchenrevenue',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
