# Generated by Django 5.0.6 on 2024-09-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_category_created_by_category_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
    ]
