# Generated by Django 5.0.6 on 2024-08-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chores', models.CharField(blank=True, max_length=60)),
                ('start_date', models.CharField(blank=True, max_length=60)),
                ('end_date', models.CharField(blank=True, max_length=120)),
                ('time', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
